cronjob:
  name: velero-annotate-resources
  schedule: "*/5 * * * *"
  image: bitnami/kubectl:latest
  serviceAccountName: annotate-resources-service-account

targets:
  - kind: pod
    name: fiware-fortesie-authzforce
    key: backup.velero.io/backup-volumes
    value: "authzforce"
    namespace: fortesie