apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.cronjob.serviceAccountName }}
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            command:
            - /bin/sh
            - -c
            - |
              {{- range $target := .Values.targets }}
              kubectl get {{ $target.kind }} -n fortesie -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep '^{{ $target.name }}' | head -n 1 && \
              kubectl annotate {{ $target.kind }} $(kubectl get {{ $target.kind }} -n fortesie -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep '^{{ $target.name }}' | head -n 1) {{ $target.key }}="{{ $target.value }}" --overwrite -n {{ $target.namespace }} && \
              {{- end }}
              echo Done!
          restartPolicy: OnFailure
