apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.cronjob.serviceAccountName }}
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            command:
            - /bin/sh
            - -c
            - >
              {{- range $target := .Values.targets }}
                kubectl annotate {{ .Values.target.kind }} {{ .Values.target.name }} {{ .Values.target.key }}="{{ .Values.target.value }}" --overwrite -n {{ .Values.target.namespace }}
              {{- end }}
          restartPolicy: OnFailure
