apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-annotator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "watch", "patch"]
